### ISSUE TITLE
line 1 column 1 Issue

### ISSUE THREAD

**Issue by michaelr278** [iranathan/robloxapi#13]
There is a issue with the sendTrade()

This is what I use:

```PY
import robloxapi;
cookie = 'MY COOKIE'
rbx = robloxapi.client(cookie)

rbx.Trade.sendTrade(345467478,['55224802'],['1365767'])
```

Error:
```File "C:\python\lib\site-packages\robloxapi\Trade.py", line 116, in sendTrade
    return json.loads(r)
  File "C:\python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by iranathan** [comment]
im pretty sure this is a error with the data i am sending to roblox i will look into it

**Comment by Jaguar-515** [comment]
Any update on this situation? @iranathan

**Comment by sbhadr** [comment]
I've added pull-request as a way around that + a flag if you want to immediately abort. Should remedy the issue. I wasn't able to reproduce this particular error on my side, however, the error is the result of response when it doesn't send a JSON. Since it's trying to load response as a JSON that's not valid, it errors.
